### ISSUE TITLE
RangeError: "size" argument must not be larger than 2147483647

### ISSUE THREAD

**Issue by paazmaya** [paazmaya/tozan#2]
```
Processing 16773 files [##############################################--------------------------] 64%buffer.js:182
    throw err;
    ^

RangeError: "size" argument must not be larger than 2147483647
    at Function.Buffer.allocUnsafe (buffer.js:209:3)
    at tryCreateBuffer (fs.js:530:21)
    at Object.fs.readFileSync (fs.js:569:14)
    at Function.hasha.fromFileSync (node_modules/hasha/index.js:65:45)
    at getMeta (index.js:142:24)
```

Do something!

**Comment by paazmaya** [comment]
Perhaps on a huge files like that, use `shasum` command line tool?

```sh
shasum --algorithm 256 filepath
```

or with OpenSSL:

```sh
openssl dgst -sha256 filepath
```

**Comment by paazmaya** [comment]
Third option could be to use `sha256` from core-utils, but not sure if it is available in Windows....
